using System.Windows;
using PocketBridge.Core.Models;
using PocketBridge.Core.Services;

namespace PocketBridge.App;

public partial class ExperimentalWindow : Window
{
    private readonly AndroidDevice _device; private readonly IP3CapabilityService _capabilities; private readonly IGamepadService _gamepads; private readonly IInputBackendService _input; private readonly IVirtualDisplayService _displays; private readonly ILanServerService _lan; private readonly IRemoteSessionService _remote; private readonly IAutomationService _automation; private readonly IAuditLogService _audit; private readonly IEmbeddedSessionManager _embeddedSessions; private HidOtgCapabilities? _inputCapabilities; private DisplayCapabilities? _displayCapabilities; private Guid? _remoteId;
    public ExperimentalWindow(AndroidDevice device, IP3CapabilityService capabilities, IGamepadService gamepads, IInputBackendService input, IVirtualDisplayService displays, ILanServerService lan, IRemoteSessionService remote, IAutomationService automation, IAuditLogService audit, IEmbeddedSessionManager embeddedSessions) { _device = device; _capabilities = capabilities; _gamepads = gamepads; _input = input; _displays = displays; _lan = lan; _remote = remote; _automation = automation; _audit = audit; _embeddedSessions = embeddedSessions; InitializeComponent(); DeviceText.Text = $"{device.FriendlyName} — {Redact(device.Serial)}"; Loaded += async (_, _) => await LoadAsync(); Closed += async (_, _) => await _input.StopOtgAsync(); }
    private async Task LoadAsync() { _inputCapabilities = await _capabilities.DetectInputAsync(_device.Serial); _displayCapabilities = await _capabilities.DetectDisplaysAsync(_device.Serial); InputStatus.Text = $"HID keyboard: {_inputCapabilities.HidKeyboard}\nHID mouse: {_inputCapabilities.HidMouse}\nOTG: {_inputCapabilities.Otg}\n{_inputCapabilities.Explanation}"; GamepadStatus.Text = _gamepads.Current.FirstOrDefault()?.Connected == true ? "Gamepad detected — Controller 1" : "No XInput gamepad detected"; DisplayStatus.Text = $"Virtual display: {_displayCapabilities.VirtualDisplay}\n{_displayCapabilities.Explanation}"; DisplaysList.ItemsSource = _displayCapabilities.Displays; Create720Button.IsEnabled = Create1080Button.IsEnabled = _displayCapabilities.VirtualDisplay == CapabilityState.Supported; OtgButton.IsEnabled = _inputCapabilities.Otg is CapabilityState.RequiresExclusiveConnection; RefreshRules(); }
    private async void Otg_Click(object sender, RoutedEventArgs e) { if (MessageBox.Show("OTG disables mirroring and may take exclusive USB ownership. Continue?", "OTG control mode", MessageBoxButton.YesNo, MessageBoxImage.Warning) == MessageBoxResult.Yes) await _input.StartOtgAsync(); }
    private async void Create720_Click(object sender, RoutedEventArgs e) => await _displays.StartAsync(_device, new(1280, 720, 240)); private async void Create1080_Click(object sender, RoutedEventArgs e) => await _displays.StartAsync(_device, new(1920, 1080, 320));
    private async void LanStart_Click(object sender, RoutedEventArgs e) { try { var permissions = RemotePermission.ViewScreen | (AllowControlBox.IsChecked == true ? RemotePermission.ControlTouch | RemotePermission.KeyboardInput | RemotePermission.DeviceButtons : RemotePermission.None); var created = _remote.Create(permissions, TimeSpan.FromMinutes(15)); _remoteId = created.Session.Id; var origin = $"http://{BindBox.Text.Trim()}:27183"; await _lan.StartAsync(new(true, BindBox.Text.Trim(), 27183, origin), created.Token); LanStatus.Text = $"{(AllowControlBox.IsChecked == true ? "Controlled" : "View-only")}: {_lan.Address}?token={Uri.EscapeDataString(created.Token)}\nPairing code: {created.PairingCode}\nExpires: {created.Session.ExpiresAt.LocalDateTime:t}"; } catch (Exception exception) { LanStatus.Text = exception.Message; } }
    private async void LanStop_Click(object sender, RoutedEventArgs e) { await _lan.StopAsync(); if (_remoteId is { } id) _remote.Revoke(id); _remoteId = null; LanStatus.Text = "LAN access disabled; session revoked."; }
    private async void AddRule_Click(object sender, RoutedEventArgs e) { await _automation.SaveAsync(new(Guid.NewGuid(), "Screenshot on connect", false, AutomationTrigger.DeviceConnected, AutomationAction.TakeScreenshot, AutomationRisk.Safe, _device.FriendlyName, RemotePermission.ViewScreen)); RefreshRules(); }
    private async void DuplicateRule_Click(object sender, RoutedEventArgs e) { if (RulesGrid.SelectedItem is AutomationRule rule) { await _automation.SaveAsync(rule with { Id = Guid.NewGuid(), Name = rule.Name + " copy", Enabled = false }); RefreshRules(); } }
    private async void DeleteRule_Click(object sender, RoutedEventArgs e) { if (RulesGrid.SelectedItem is AutomationRule rule) { await _automation.DeleteAsync(rule.Id); RefreshRules(); } }
    private void Audit_Click(object sender, RoutedEventArgs e) => new AuditLogWindow(_audit) { Owner = this }.Show();
    private async void DisplayOpen_Click(object sender, RoutedEventArgs e) { if (DisplaysList.SelectedItem is DisplayDescriptor display) await _embeddedSessions.StartAsync(_device, new ScrcpyLaunchOptions { DisplayId = display.DisplayId }); }
    private async void DisplayStop_Click(object sender, RoutedEventArgs e) { if (DisplaysList.SelectedItem is DisplayDescriptor display) await _embeddedSessions.StopAsync(_device.Serial, display.DisplayId); }
    private void RefreshRules() => RulesGrid.ItemsSource = _automation.Rules;
    private static string Redact(string serial) => serial.Length <= 4 ? "••••" : $"••••{serial[^4..]}";
}
