using System.Windows;
using System.Windows.Controls;
using System.Text.RegularExpressions;
using PocketBridge.Core.Models;
using PocketBridge.Core.Services;
using PocketBridge.App.Localization;

namespace PocketBridge.App;

public partial class ExperimentalWindow : Window
{
    private readonly AndroidDevice _device; private readonly IP3CapabilityService _capabilities; private readonly IGamepadService _gamepads; private readonly IInputBackendService _input; private readonly IVirtualDisplayService _displays; private readonly ILanServerService _lan; private readonly IRemoteSessionService _remote; private readonly IAutomationService _automation; private readonly IAuditLogService _audit; private readonly IEmbeddedSessionManager _embeddedSessions; private readonly IScrcpyService _scrcpy; private readonly IAdbService _adb; private HidOtgCapabilities? _inputCapabilities; private DisplayCapabilities? _displayCapabilities; private Guid? _remoteId;
    public ExperimentalWindow(AndroidDevice device, IP3CapabilityService capabilities, IGamepadService gamepads, IInputBackendService input, IVirtualDisplayService displays, ILanServerService lan, IRemoteSessionService remote, IAutomationService automation, IAuditLogService audit, IEmbeddedSessionManager embeddedSessions, IScrcpyService scrcpy, IAdbService adb) { _device = device; _capabilities = capabilities; _gamepads = gamepads; _input = input; _displays = displays; _lan = lan; _remote = remote; _automation = automation; _audit = audit; _embeddedSessions = embeddedSessions; _scrcpy = scrcpy; _adb = adb; InitializeComponent(); DeviceText.Text = $"{device.FriendlyName} — {Redact(device.Serial)}"; Loaded += async (_, _) => await LoadAsync(); Closed += async (_, _) => await _input.StopOtgAsync(); }
    private async Task LoadAsync() { _inputCapabilities = await _capabilities.DetectInputAsync(_device.Serial); _displayCapabilities = await _capabilities.DetectDisplaysAsync(_device.Serial); InputStatus.Text = LocalizationService.Current.Format("P3_HidStatusFormat", _inputCapabilities.HidKeyboard, _inputCapabilities.HidMouse, _inputCapabilities.Otg, _inputCapabilities.Explanation); GamepadStatus.Text = LocalizationService.Current[_gamepads.Current.Any(item => item.Connected) ? "P3_GamepadDetected" : "P3_GamepadMissing"]; DisplayStatus.Text = LocalizationService.Current.Format("P3_VirtualStatusFormat", _displayCapabilities.VirtualDisplay, _displayCapabilities.Explanation); RefreshDisplayTree(); Create720Button.IsEnabled = Create1080Button.IsEnabled = _displayCapabilities.VirtualDisplay == CapabilityState.Supported; OtgButton.IsEnabled = _inputCapabilities.Otg is CapabilityState.RequiresExclusiveConnection; RefreshRules(); }
    private async void Otg_Click(object sender, RoutedEventArgs e) { if (MessageBox.Show(LocalizationService.Current["P3_OtgConfirm"], LocalizationService.Current["P3_InputOtg"], MessageBoxButton.YesNo, MessageBoxImage.Warning) == MessageBoxResult.Yes) await _input.StartOtgAsync(); }
    private async void Create720_Click(object sender, RoutedEventArgs e) => await _displays.StartAsync(_device, new(1280, 720, 240, PackageOrNull())); private async void Create1080_Click(object sender, RoutedEventArgs e) => await _displays.StartAsync(_device, new(1920, 1080, 320, PackageOrNull()));
    private async void LanStart_Click(object sender, RoutedEventArgs e) { try { var permissions = RemotePermission.ViewScreen | (AllowControlBox.IsChecked == true ? RemotePermission.ControlTouch | RemotePermission.KeyboardInput | RemotePermission.DeviceButtons : RemotePermission.None); var created = _remote.Create(permissions, TimeSpan.FromMinutes(15)); _remoteId = created.Session.Id; var origin = $"http://{BindBox.Text.Trim()}:27183"; await _lan.StartAsync(new(true, BindBox.Text.Trim(), 27183, origin), created.Token); LanStatus.Text = LocalizationService.Current.Format("P3_LanStatusFormat", LocalizationService.Current[AllowControlBox.IsChecked == true ? "P3_Controlled" : "P3_ViewOnly"], _lan.Address, Uri.EscapeDataString(created.Token), created.PairingCode, created.Session.ExpiresAt.LocalDateTime.ToShortTimeString()); } catch (Exception exception) { LanStatus.Text = exception.Message; } }
    private async void LanStop_Click(object sender, RoutedEventArgs e) { await _lan.StopAsync(); if (_remoteId is { } id) _remote.Revoke(id); _remoteId = null; LanStatus.Text = LocalizationService.Current["P3_LanDisabled"]; }
    private async void AddRule_Click(object sender, RoutedEventArgs e) { await _automation.SaveAsync(new(Guid.NewGuid(), LocalizationService.Current["P3_ScreenshotRuleName"], false, AutomationTrigger.DeviceConnected, AutomationAction.TakeScreenshot, AutomationRisk.Safe, _device.FriendlyName, RemotePermission.ViewScreen)); RefreshRules(); }
    private async void DuplicateRule_Click(object sender, RoutedEventArgs e) { if (RulesGrid.SelectedItem is AutomationRule rule) { await _automation.SaveAsync(rule with { Id = Guid.NewGuid(), Name = rule.Name + LocalizationService.Current["P3_CopySuffix"], Enabled = false }); RefreshRules(); } }
    private async void DeleteRule_Click(object sender, RoutedEventArgs e) { if (RulesGrid.SelectedItem is AutomationRule rule) { await _automation.DeleteAsync(rule.Id); RefreshRules(); } }
    private void Audit_Click(object sender, RoutedEventArgs e) => new AuditLogWindow(_audit) { Owner = this }.Show();
    private async void DisplayOpen_Click(object sender, RoutedEventArgs e) { if (SelectedDisplay() is { } display) { await _embeddedSessions.StartAsync(_device, new ScrcpyLaunchOptions { DisplayId = display.DisplayId }); RefreshDisplayTree(); } }
    private async void DisplayExternal_Click(object sender, RoutedEventArgs e) { if (SelectedDisplay() is { } display) { await _scrcpy.StartAsync(_device, new ScrcpyLaunchOptions { DisplayId = display.DisplayId, WindowTitle = $"PocketBridge — {_device.FriendlyName} — Display {display.DisplayId}" }); RefreshDisplayTree(); } }
    private async void DisplayStop_Click(object sender, RoutedEventArgs e) { if (SelectedDisplay() is { } display) { await _embeddedSessions.StopAsync(_device.Serial, display.DisplayId); await _scrcpy.StopAsync(_device.Serial, display.DisplayId); RefreshDisplayTree(); } }
    private async void VirtualStop_Click(object sender, RoutedEventArgs e) => await _displays.StopAsync(_device.Serial);
    private async void DisplayLaunchApp_Click(object sender, RoutedEventArgs e) { if (SelectedDisplay() is not { } display || PackageOrNull() is not { } package) return; var resolved = await _adb.ExecuteAsync(_device.Serial, "shell", "cmd", "package", "resolve-activity", "--brief", package); var component = resolved.StandardOutput.Split('\n', StringSplitOptions.RemoveEmptyEntries).LastOrDefault()?.Trim(); if (!resolved.IsSuccess || string.IsNullOrWhiteSpace(component) || !component.Contains('/')) throw new InvalidOperationException(LocalizationService.Current["P3_ActivityNotFound"]); var launched = await _adb.ExecuteAsync(_device.Serial, "shell", "am", "start", "--display", display.DisplayId.ToString(), "-n", component); if (!launched.IsSuccess) throw new InvalidOperationException(launched.StandardError); }
    private void RefreshDisplayTree() { if (_displayCapabilities is null) return; DeviceDisplayRoot.Header = LocalizationService.Current.Format("P3_DisplayRootFormat", _device.FriendlyName); DeviceDisplayRoot.Items.Clear(); foreach (var display in _displayCapabilities.Displays) { var active = _embeddedSessions.Get(_device.Serial, display.DisplayId)?.IsRunning == true || _scrcpy.IsRunning(_device.Serial, display.DisplayId); var item = new TreeViewItem { Header = LocalizationService.Current.Format("P3_DisplayItemFormat", display.DisplayId, display.DisplayId == 0 ? LocalizationService.Current["P3_MainDisplay"] : "", display.Name, LocalizationService.Current[active ? "P3_Active" : "P3_Stopped"]), DataContext = display }; DeviceDisplayRoot.Items.Add(item); } }
    private DisplayDescriptor? SelectedDisplay() => (DisplaysList.SelectedItem as TreeViewItem)?.DataContext as DisplayDescriptor;
    private string? PackageOrNull() { var package = DisplayPackageBox.Text.Trim(); if (package.Length == 0) return null; if (!Regex.IsMatch(package, "^[A-Za-z][A-Za-z0-9_]*(\\.[A-Za-z0-9_]+)+$")) throw new InvalidOperationException(LocalizationService.Current["P3_InvalidPackage"]); return package; }
    private void RefreshRules() => RulesGrid.ItemsSource = _automation.Rules;
    private static string Redact(string serial) => serial.Length <= 4 ? "••••" : $"••••{serial[^4..]}";
}
